---
- name: Install python module for work with MySQL DB
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
    update_cache: true

- name: Set root password
  become: true
  community.mysql.mysql_user:
    name: 'root'
    password: "{{ mysql_root_password }}"
    host: 'localhost'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  ignore_errors: True


- name: Create admin user
  become: true
  community.mysql.mysql_user:
    name: admin
    password: "{{ mysql_admin_password  }}"
    priv: "{{ mysql_admin_privileges }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password  }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  ignore_errors: True
