---
- name: Config file for Joomla
  ansible.builtin.template:
    src: joomla.conf.j2
    dest: "/etc/nginx/sites-enabled/joomla.conf"
    mode: '0755'

- name: Create sym link for enable site in nginx
  ansible.builtin.file:
    src: "/etc/nginx/sites-enabled/joomla.conf"
    dest: "/etc/nginx/sites-available/joomla.conf"
    state: link
  notify: Nginx reload

- name: Create directory for Joomla
  ansible.builtin.file:
    path: "{{ initapps_joomla_site_dir }}"
    state: directory
    owner: "{{ initapps_nginx_user }}"
    group: "{{ initapps_nginx_user }}"
    mode: '0755'
