---
- name: Install PHP and extensions
  ansible.builtin.apt:
    name:
      - php{{ php_version }}
      - php{{ php_version }}-fpm
      - php{{ php_version }}-mysql
      - php{{ php_version }}-xml
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-curl
      - php{{ php_version }}-zip
      - php{{ php_version }}-gd
      - php{{ php_version }}-intl
      - php{{ php_version }}-soap
    state: present
    update_cache: true

- name: Ensure php-fpm is running
  ansible.builtin.service:
    name: php{{ php_version }}-fpm
    state: started
    enabled: true
